name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: build
       run: |
         cmake -S . -B build -G "Unix Makefiles"
         cmake --build build
     - name: test
       run: |
        ./builds/test/Tiled_Matrix_googletest
